version: "3"
services:
  # selenim用コンテナ(vncが走る)
  selenium:
    image: selenium/standalone-chrome:4.1.4-20220427
    ports:
      - 4444:4444   # selenium grid用
      - 7900:7900   # vnc ビューワー用
    volumes:
      - /dev/shm:/dev/shm
  app:
    build: .
    volumes:
      - .:/app
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    tty: true

